Stock_Assist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stockassist.urls')),
]

stockassist/urls.py
from django.urls import path
from . import views

app_name = 'stockassist'
urlpatterns = [
    path('', view=views.redirect_to_home, name='authcheck'),
    path('home/', view=views.homepage, name='homepage'),
    path('signup/', view=views.signup, name='signup'),
    path('login/', view=views.login_req, name='login'),
    path('logout/', view=views.logout_req, name='logout'),
    path('addstock/<str:stock_symbol>/<str:stock_name>/', view=views.add_stock_to_watchlist, name='addstock'),
    path('deletestock/<str:stock_symbol>/', view=views.delete_from_watchlist, name='deletestock'),
    path('ajax/requests/search/', view=views.search_stock, name='searchstock'),
    path('ajax/requests/fetch_price/', view=views.get_stock_price, name='fetch_price'),
    path('error/',view=views.error, name='error'),
    path('ajax/requests/get_opens/', view=views.fetch_open_market_price, name='getOpenPrices'),
    path('ajax/getInfo/', view=views.stock_info_module, name='getInfo'),
    path('ajax/getChartData', view=views.stockChartData, name='getChartData'),
    path('myportfolio/', view=views.myportfolio, name='myportfolio'),

]

stockassist/models.py
from django.db import models
# Create your models here.

#Creating a stock watchlist model with minimal details
class watchlist_stocks_current(models.Model):
    stk_symbol = models.CharField(max_length=50, null=False, default='NULL_FIELD')
    stk_name = models.CharField(max_length=200, null=False, default='NULL_FIELD')
    stk_price = models.FloatField(null=False, default=-1.0)
    watchlist_user = models.CharField(max_length=200, null=False, default='NULL_FIELD')

class portfolio_profit(models.Model):
    watchlist_user = models.CharField(max_length=200, null=False, default='NULL_FIELD')
    stock = models.CharField(max_length=50, null=False, default='NULL_FIELD')
    price_purchased = models.FloatField(null=False, default=-1.0)
    num_stocks = models.IntegerField(null=False, default=0)

stockassist/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
import django.contrib.auth as auth

from stockassist.cloudant_connect import fetch_current_prices, fetch_intraday_prices, get_open_prices
from stockassist.stock_operations import fetch_quote, getHistoricalData, is_market_open
from .ajax_templates import add_stock_to_db, remove_stock_from_db, search, topStocks, update_price_in_local_db
from stockassist.models import portfolio_profit, watchlist_stocks_current

# Create your views here.

def homepage(request):
    if request.method == 'GET':
        if not request.user.is_authenticated:
            return redirect('stockassist:authcheck')
        TOPSTOCKS = topStocks()
        context = {
            'stock_result': TOPSTOCKS
        }
        if request.user.is_authenticated:
            context['market_open'] = is_market_open()
            current_stock_price = fetch_current_prices()
            update_price_in_local_db(current_stock_price['prices'], request.user.username)
            my_stocks = watchlist_stocks_current.objects.filter(watchlist_user = request.user.username)
            context['watchlist_stocks'] = my_stocks
        return render(request, 'stockassist/index.html', context=context)
    else:
        error(request, 'Looks like you wandered off')

def redirect_to_home(request):
    if request.method == 'GET':
        if not request.user.is_authenticated:
            context = {
                'notauthenticated': False
            }
            return render(request, 'stockassist/loginpage.html', context)
        return redirect('stockassist:homepage')
    else:
        error(request, 'Looks like you wandered off')
def signup(request):
    if request.method == 'GET':
        return render(request, 'stockassist/signup.html')
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['pwd']
        firstName = request.POST['fname']
        lastName = request.POST['lname']
        emailid = request.POST['emailid']
        userExist = False
        try:
            User.objects.get(username=username)
            userExist = True
        except:
            pass
        if not userExist:
            user = User.objects.create_user(username=username, password=password, first_name=firstName, last_name=lastName, email=emailid)
            auth.login(request, user)
            return redirect('stockassist:homepage')
        else:
            context = {
                'userExists': True,
                'fname': firstName,
                'lname': lastName,
                'emailid': emailid
            }
            return render(request, 'stockassist/signup.html', context=context)
    else:
        return redirect('stockassist:homepage')

def login_req(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['pwd']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('stockassist:homepage')
        else:
            context = {
                'notauthenticated': True
            }
            return render(request, 'stockassist/loginpage.html', context)
    else:
        return render(request, 'stockassist/loginpage.html')

def logout_req(request):
    if request.method == 'GET':
        auth.logout(request)
        return redirect('stockassist:authcheck')
    else:
        error(request, 'Looks like you wandered off')

def search_stock(request):
    if request.method == 'GET':
        str = request.GET['searchStr']
        result = search(str)
        return JsonResponse({
            'stock_result': result
        })
    else:
        error(request, 'Looks like you wandered off')

def add_stock_to_watchlist(request, stock_symbol, stock_name):
    if request.method == 'GET':
        if request.user.is_authenticated:
            stock_in_watchlist = False
            try:
                stock = watchlist_stocks_current.objects.get(stk_symbol=stock_symbol, watchlist_user=request.user.username)
                stock_in_watchlist = True
            except:
                pass
            if not stock_in_watchlist:
                stk = watchlist_stocks_current(
                    stk_symbol=stock_symbol, stk_name=stock_name, 
                    watchlist_user=request.user.username)
                stk.save()
                add_stock_to_db(stock_symbol)
                return redirect('stockassist:homepage')
            else:
                return redirect('stockassist:homepage')
        else:
            return redirect('stockassist:authcheck')
    else:
        error(request, 'Looks like you wandered off')

def delete_from_watchlist(request, stock_symbol):
    if request.method == 'GET':
        try:
            watchlist_stocks_current.objects.get(stk_symbol=stock_symbol, watchlist_user=request.user.username).delete()
        except:
            pass
        try:
            stk = watchlist_stocks_current.objects.get(stk_symbol=stock_symbol)
        except:
            remove_stock_from_db(stock_symbol)
        finally:
            return redirect('stockassist:homepage')
    else:
        error(request, 'Looks like you wandered off')

def get_stock_price(request):
    if request.method == 'GET':
        if not is_market_open():
            return JsonResponse({'market':'closed'})
        else:
            current_stock_price = fetch_current_prices()
            return JsonResponse({'market':'open', 'prices': current_stock_price['prices'], 'time': current_stock_price['time']})

def fetch_open_market_price(request):
    if request.method == 'GET':
        prices = get_open_prices()
        return JsonResponse({'open': prices})
    else:
        error(request, 'Looks like you wandered off')

def stock_info_module(request):
    if request.method == 'GET':
        stock = (request.GET['stock']).format('.')
        data = {}
        if stock != '^BSESN':
            data = fetch_quote(stock)
        chart_dataset = fetch_intraday_prices(stock)
        return JsonResponse({'fundamental':data, 'chart_data': chart_dataset})
    else:
        error(request, message='Looks like you wandered off')

def stockChartData(request):
    if request.method == 'GET':
        stock = request.GET['stock']
        if stock == 'SENSEX':
            stock = '^BSESN'
        if (request.GET['period'] == '1D'):    
            dataPoints = fetch_intraday_prices(stock.format('.'))
        else:
            dataPoints = getHistoricalData(stock.format('.'), request.GET['period'])
        return JsonResponse(dataPoints)
    else:
        error(request, message='Looks like you wandered off')

def myportfolio(request):
    if request.method == 'GET':
        if (request.user.is_authenticated):
            current_stock_price = fetch_current_prices()
            update_price_in_local_db(current_stock_price['prices'], request.user.username)
            my_stocks = watchlist_stocks_current.objects.filter(watchlist_user = request.user.username)
            portfolio_stocks = portfolio_profit.objects.filter(watchlist_user = request.user.username)
            #Modify both dicts to create 1 non redundant dict
            context = {'watchlist_stocks': my_stocks, 'portfolio_stocks': portfolio_stocks}
            return render(request, 'stockassist/myportfolio.html', context)
        else:
            return redirect('stockassist:authcheck')
    else:
        error(request, message='looks like you wandered off')

def add_to_portfolio(request):
    if request.method == 'GET':
        pass
    else:
        error(request, message='looks like you wandered off')

def remove_from_portfolio(request):
    pass

def error(request, message=''):
    return render(request, 'stockassist/error.html', {'errormessage': message})

stockassist/templates/stockassist/error.html
<html lang="en">
    <head>
        {%load static%}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Error</title>
    </head>
    <body background="{%static 'stockassist/Login.jpg'%}">
        <h1 class="text-danger" style="text-align: center;">Error</h1>
        <br>
        <hr>
        <h2 class="text-warning" style="text-align: center;">{{errormessage}}</h2>
        <br>
        <br>
        <h3 class="text-secondary" style="text-align: center;">Redirecting you to the homepage...</h3>
        <script>
            setTimeout(() => {
                open('../','_top')
            }, 4000);
        </script>
    </body>
</html>

stockassist/templates/stockassist/loginpage.html
<html lang="en-gb">
    <head>
        {%load static%}
        <meta charset="UTF-8">
        <meta name="description" content="This website is about helping you manage your portfolio">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <script src="{%static 'stockassist/UI.js'%}"></script>
        <title>Login</title>
    </head>
    <body background="{%static 'stockassist/Login.jpg'%}">
        <nav class="navbar navbar-expand-sm bg-light justify-content-center">
            <div class="navbar-nav">
                <a href="{%url 'stockassist:homepage'%}" class="navbar-brand px-3 py-2"><h2>Stock Assist</h2></a>
            </div>
        </nav>
        <br>
        <div class="container">
            <h1 class="text-success" style="text-align: center;">Login</h1>
            <br>
            {%if notauthenticated%}
                <div class="alert alert-warning alert-dismissible fade show" id="errorbox">
                    <strong id="errormessages">Invalid credentials. Please try again</strong>
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                </div>
            {%endif%}    
            <form method="post" action='{%url "stockassist:login"%}' style="width: 60%; margin: auto;">
                {%csrf_token%}
                <div class="form-group">
                    <label for="username">Username: </label>
                    <input type="text" class="form-control" name="username" id="username" required>
                </div>
                <label for="pwd">Password: </label>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" name="pwd" id="pwd" required>
                    <div class="input-group-append">
                        <button type="button" class="btn btn-light float-right" onclick="changeVis()">
                            <i class="material-icons" id="togglePwdIcon">visibility_off</i>
                        </button>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-block" id="Login_button" onsubmit="login()">Log in</button>
            </form>
            <br>
            <hr>
            <h4 class="text-secondary" style="text-align: center;">or</h2>
            <a class="btn btn-danger btn-block" style="width: 60%; margin: auto;" href="{%url 'stockassist:signup'%}">Sign up</a>
        </div>
    </body>
</html>

stockassist/templates/stockassist/myportfolio.html
<html lang="en-us">
    <head>
        {%load static%}
        <meta charset="UTF-8">
        <meta name="description" content="This website is about helping you manage your portfolio">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{%static 'stockassist/UI.css'%}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="{%static 'stockassist/UI.js'%}"></script>
        <title>My portfolio</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-light">
            <div class="navbar-nav w-100">
                <a class="navbar-brand px-3 py-2 flex-fill" href="#"><h2>Stock Assist</h2></a>
                {%if user.is_authenticated%}
                    <span class="nav-item px-3 py-2 flex-fill">
                        <span class="dropdown float-right">
                            <a href="#" class="nav-link dropdown-toggle" id="userdropdown" data-toggle="dropdown">Welcome, {{user.first_name}}</a>
                            <div class="dropdown-menu px-1">
                                {%if watchlist_stocks.0%}
                                <a href="{%url 'stockassist:homepage'%}" class="dropdown-item mx-1">My watchlist</a>
                                <div class="dropdown-divider"></div>
                                {%endif%}
                                <a href="{%url 'stockassist:logout'%}" class="btn btn-outline-danger btn-block btn-sm">Logout</a>
                            </div>
                        </span>
                    </span>
                {%endif%}
            </div>
        </nav>
        <div class="container-fluid">
            <br>
            <div style="height: auto;">
                <h1 class="text-dark" style="float: left;">My portfolio</h1>
                <button onclick="javascript:void(0)" class="btn btn-light text-primary" type="button" style="float: right;"><i class="material-icons" style="vertical-align: middle;">add</i> Add stock to portfolio</button>
            </div>
            <br>
            <br>
            <div>
                <!--Add portfolio stocks here-->
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Stock</th>
                            <th>Company Name</th>
                            <th>Current Price</th>
                            <th>Purchased at</th>
                            <th>No. of stocks</th>
                            <th>Total profit/loss</th>
                            <th>Total change</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>

    </body>
</html>

stockassist/templates/stockassist/signup.html
<html lang="en-gb">
    <head>
        {%load static%}
        <meta charset="UTF-8">
        <meta name="description" content="This website is about helping you manage your portfolio">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <script src="{%static 'stockassist/UI.js'%}"></script>
        <title>Sign Up</title>
    </head>
    <body background="{%static 'stockassist/Login.jpg'%}">
        <nav class="navbar navbar-expand-sm bg-light justify-content-center">
            <div class="navbar-nav">
                <a href="{%url 'stockassist:homepage'%}" class="navbar-brand px-3 py-2"><h2>Stock Assist</h2></a>
            </div>
        </nav>
        <div class="container-fluid">
            <br>
            <h3 class="text-danger text-center">Sign Up</h3>
            <form method="POST" action="{% url 'stockassist:signup'%}" style="width: 60%; margin: auto;">
                {%csrf_token%}
                <div class="form-group">
                    <label for="username">Username: </label>
                    <input type="text" placeholder="Enter username" class="form-control" name="username" id="username" required>
                </div>
                {%if userExists%}
                    <div class="alert alert-danger alert-dismissable fade show">
                        <strong>Username is already taken</strong>
                        <button class="close" data-dismiss="alert">&times;</button>
                    </div>
                    <div class="form-group">
                        <label for="fname">First Name: </label>
                        <input type="text" class="form-control" name="fname" id="fname" placeholder="Enter first name" value="{{fname}}" required>
                    </div>
                    <div class="form-group">
                        <label for="lname">Last Name: </label>
                        <input type="text" class="form-control" name="lname" id="lname" placeholder="Enter last name" value="{{lname}}" required>
                    </div>
                    <div class="form-group">
                        <label for="emailid">Email ID: </label>
                        <input type="email" class="form-control" name="emailid" id="emailid" placeholder="Enter email id" value="{{emailid}}" required>
                    </div>
                {%else%}
                    <div class="form-group">
                        <label for="fname">First Name: </label>
                        <input type="text" class="form-control" name="fname" id="fname" placeholder="Enter first name" required>
                    </div>
                    <div class="form-group">
                        <label for="lname">Last Name: </label>
                        <input type="text" class="form-control" name="lname" id="lname" placeholder="Enter last name" required>
                    </div>
                    <div class="form-group">
                        <label for="emailid">Email ID: </label>
                        <input type="email" class="form-control" name="emailid" id="emailid" placeholder="Enter email id" required>
                    </div>
                {%endif%}
                <label for="pwd">Password: </label>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" name="pwd" id="pwd" placeholder="Enter password" required>
                    <div class="input-group-append">
                        <button type="button" class="btn btn-light float-right" onclick="changeVis()">
                            <i class="material-icons" id="togglePwdIcon">visibility_off</i>
                        </button>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-block" id="Signup_button" onsubmit="signup()">Sign Up</button>
            </form>
        </div>
    </body>
</html>